version: '3'
networks:
  default:
    name: my_app_network

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - default
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tradeDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qushus@0304
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_started # Zookeeper doesn't have a clear health endpoint
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default
    volumes:
      - kafka_data:/var/lib/kafka
        
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    
    networks:
      - default
    volumes:
      - schema_registry_data:/var/lib/schema-registry

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - default
    volumes:
      - kafka_ui_data:/var/lib/kafka-ui

  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - default
    

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    
    ports:
      - "9090:9090"
    networks:
      - default

  tempo:
    image: grafana/tempo:2.2.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
   
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin
    networks:
      - default

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - default

  api-gateway:
    container_name: api-gateway
    image: sakina03/api-gateway:latest
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      trade-service:
        condition: service_started
      settlement-service:
        condition: service_started
      auth-service:
        condition: service_started
      tempo: # Add dependency on tempo
        condition: service_started 
    networks:
      - default
    

  trade-service:
    container_name: trade-service
    image: sakina03/trade-service:latest
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_started
    
    networks:
      - default
        

  settlement-service:
    container_name: settlement-service
    image: sakina03/settlement-service:latest
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default
    
  auth-service:
    container_name: auth-service
    image: sakina03/auth-service:latest
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default
    

  fund-service:
    container_name: fund-service
    image: sakina03/fund-service:latest
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default

   


  trade-frontend:
    container_name: trade-frontend
    image: sakina03/trade-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - default
    

 


volumes:
  zookeeper_data:
  postgres_data:
  kafka_data:
  schema_registry_data:
  kafka_ui_data:
 
  
  