global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:9000"] # Use the Docker service name and container port
  - job_name: "trade-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["trade-service:8090"] # Use the Docker service name and container port
        labels:
          application: "trade Service"
  - job_name: "risk-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["risk-service:8089"] # Use the Docker service name and container port
        labels:
          application: "risk Service"
  - job_name: "settlement-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["settlement-service:8088"] # Use the Docker service name and container port
        labels:
          application: "settlement Service"
