name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Qushus@0304
          POSTGRES_DB: fundservice
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push trade-service image
        run: |
          mvn -f trade-service/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/trade-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/trade-service:latest

      - name: Build and push risk-service image
        run: |
          mvn -f risk-service/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/risk-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/risk-service:latest

      - name: Build and push settlement-service image
        run: |
          mvn -f settlement-service/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/settlement-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/settlement-service:latest

      - name: Build and push auth-service image
        run: |
          mvn -f AuthService/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and push api gateway image
        run: |
          mvn -f api-gateway/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and push fund-service image
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fundservice
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Qushus@0304
        run: |
          mvn -f FundService/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/fund-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fund-service:latest

      - name: Build and push notification-service image
        run: |
          mvn -f NotificationService/pom.xml spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
